SHARED_RADIUS = {
    "button": "8px",
    "pill": "16px",
    "navbar": "24px",
    "home_button": "18px",
}

SHARED_SIZE = {
    "home_button": "36px",
    "nav_button_height": "32px",
    "nav_home_icon": "25px",
    "nav_button_horizontal_padding": "18px",
}


def create_theme(name: str, color: dict[str, str]) -> dict:
    return {
        "name": name,
        "color": color,
        "radius": SHARED_RADIUS,
        "size": SHARED_SIZE,
    }


LIGHT_THEME = create_theme(
    "light",
    {
        "app_bg": "#f3f5f7",
        "panel_bg": "#e2e6ea",
        "panel_bg_emphasis": "#d2d8df",
        "content_bg": "#f8f9fb",
        "button_bg": "#d8dde3",
        "button_hover_bg": "#cfd6dd",
        "button_active_bg": "#bfc8d2",
        "text_primary": "#1f2328",
        "text_secondary": "#5b6470",
        "border": "#c7cdd4",
        "home_button_bg": "#ffffff",
        "home_button_text": "#111111",
        "home_button_hover_bg": "rgba(255, 255, 255, 0.9)",
        "home_button_pressed_bg": "rgba(0, 0, 0, 0.1)",
        "nav_button_bg": "transparent",
        "nav_button_text": "#2c2c2c",
        "nav_button_hover_bg": "rgba(255, 255, 255, 0.5)",
        "nav_button_pressed_bg": "rgba(0, 0, 0, 0.1)",
        "nav_button_active_bg": "#ffffff",
        "nav_button_active_text": "#111111",
    },
)

DARK_THEME = create_theme(
    "dark",
    {
        "app_bg": "#1b1d22",
        "panel_bg": "#2a2d33",
        "panel_bg_emphasis": "#202329",
        "content_bg": "#202329",
        "button_bg": "#343943",
        "button_hover_bg": "#404652",
        "button_active_bg": "#4a5160",
        "text_primary": "#e8eaed",
        "text_secondary": "#aab2bf",
        "border": "#3b4048",
        "home_button_bg": "#ffffff",
        "home_button_text": "#111111",
        "home_button_hover_bg": "rgba(255, 255, 255, 0.9)",
        "home_button_pressed_bg": "rgba(0, 0, 0, 0.1)",
        "nav_button_bg": "transparent",
        "nav_button_text": "#e8eaed",
        "nav_button_hover_bg": "rgba(255, 255, 255, 0.2)",
        "nav_button_pressed_bg": "rgba(0, 0, 0, 0.1)",
        "nav_button_active_bg": "#ffffff",
        "nav_button_active_text": "#111111",
    },
)

STEEL_THEME = create_theme(
    "steel",
    {
        "app_bg": "#20262c",
        "panel_bg": "#2f3841",
        "panel_bg_emphasis": "#263039",
        "content_bg": "#242b32",
        "button_bg": "#394550",
        "button_hover_bg": "#45535f",
        "button_active_bg": "#516171",
        "text_primary": "#eef3f7",
        "text_secondary": "#b8c4cc",
        "border": "#53616c",
        "home_button_bg": "#f4f7f9",
        "home_button_text": "#172027",
        "home_button_hover_bg": "rgba(244, 247, 249, 0.9)",
        "home_button_pressed_bg": "rgba(0, 0, 0, 0.18)",
        "nav_button_bg": "transparent",
        "nav_button_text": "#eef3f7",
        "nav_button_hover_bg": "rgba(255, 255, 255, 0.16)",
        "nav_button_pressed_bg": "rgba(0, 0, 0, 0.2)",
        "nav_button_active_bg": "#f4f7f9",
        "nav_button_active_text": "#172027",
    },
)

GRAPHITE_THEME = create_theme(
    "graphite",
    {
        "app_bg": "#171717",
        "panel_bg": "#242424",
        "panel_bg_emphasis": "#1d1d1d",
        "content_bg": "#1f1f1f",
        "button_bg": "#303030",
        "button_hover_bg": "#3a3a3a",
        "button_active_bg": "#464646",
        "text_primary": "#f1f1f1",
        "text_secondary": "#b8b8b8",
        "border": "#4a4a4a",
        "home_button_bg": "#f2f2f2",
        "home_button_text": "#151515",
        "home_button_hover_bg": "rgba(242, 242, 242, 0.9)",
        "home_button_pressed_bg": "rgba(0, 0, 0, 0.18)",
        "nav_button_bg": "transparent",
        "nav_button_text": "#f1f1f1",
        "nav_button_hover_bg": "rgba(255, 255, 255, 0.14)",
        "nav_button_pressed_bg": "rgba(0, 0, 0, 0.24)",
        "nav_button_active_bg": "#f2f2f2",
        "nav_button_active_text": "#151515",
    },
)

OCEAN_THEME = create_theme(
    "ocean",
    {
        "app_bg": "#10232b",
        "panel_bg": "#17323d",
        "panel_bg_emphasis": "#0f2a35",
        "content_bg": "#12303a",
        "button_bg": "#1e4652",
        "button_hover_bg": "#285765",
        "button_active_bg": "#326878",
        "text_primary": "#e9f7fb",
        "text_secondary": "#a9cbd5",
        "border": "#3a6875",
        "home_button_bg": "#e9f7fb",
        "home_button_text": "#0f2530",
        "home_button_hover_bg": "rgba(233, 247, 251, 0.9)",
        "home_button_pressed_bg": "rgba(0, 0, 0, 0.18)",
        "nav_button_bg": "transparent",
        "nav_button_text": "#e9f7fb",
        "nav_button_hover_bg": "rgba(233, 247, 251, 0.16)",
        "nav_button_pressed_bg": "rgba(0, 0, 0, 0.22)",
        "nav_button_active_bg": "#e9f7fb",
        "nav_button_active_text": "#0f2530",
    },
)

FOREST_THEME = create_theme(
    "forest",
    {
        "app_bg": "#17231c",
        "panel_bg": "#24352b",
        "panel_bg_emphasis": "#1d2b23",
        "content_bg": "#1c2d23",
        "button_bg": "#31483a",
        "button_hover_bg": "#3c5948",
        "button_active_bg": "#496a56",
        "text_primary": "#edf6ef",
        "text_secondary": "#b7c9bd",
        "border": "#55705f",
        "home_button_bg": "#edf6ef",
        "home_button_text": "#142117",
        "home_button_hover_bg": "rgba(237, 246, 239, 0.9)",
        "home_button_pressed_bg": "rgba(0, 0, 0, 0.18)",
        "nav_button_bg": "transparent",
        "nav_button_text": "#edf6ef",
        "nav_button_hover_bg": "rgba(237, 246, 239, 0.14)",
        "nav_button_pressed_bg": "rgba(0, 0, 0, 0.22)",
        "nav_button_active_bg": "#edf6ef",
        "nav_button_active_text": "#142117",
    },
)

AMBER_THEME = create_theme(
    "amber",
    {
        "app_bg": "#2b251b",
        "panel_bg": "#3a3122",
        "panel_bg_emphasis": "#302817",
        "content_bg": "#332a1b",
        "button_bg": "#4a3c25",
        "button_hover_bg": "#5b4a2c",
        "button_active_bg": "#6d5935",
        "text_primary": "#fff4dc",
        "text_secondary": "#d7c39a",
        "border": "#735f3b",
        "home_button_bg": "#fff4dc",
        "home_button_text": "#271d0e",
        "home_button_hover_bg": "rgba(255, 244, 220, 0.9)",
        "home_button_pressed_bg": "rgba(0, 0, 0, 0.2)",
        "nav_button_bg": "transparent",
        "nav_button_text": "#fff4dc",
        "nav_button_hover_bg": "rgba(255, 244, 220, 0.14)",
        "nav_button_pressed_bg": "rgba(0, 0, 0, 0.24)",
        "nav_button_active_bg": "#fff4dc",
        "nav_button_active_text": "#271d0e",
    },
)

VIOLET_THEME = create_theme(
    "violet",
    {
        "app_bg": "#211b2b",
        "panel_bg": "#302740",
        "panel_bg_emphasis": "#281f36",
        "content_bg": "#292139",
        "button_bg": "#3d3154",
        "button_hover_bg": "#4a3c67",
        "button_active_bg": "#58477a",
        "text_primary": "#f4efff",
        "text_secondary": "#c8bddb",
        "border": "#63517d",
        "home_button_bg": "#f4efff",
        "home_button_text": "#1f1730",
        "home_button_hover_bg": "rgba(244, 239, 255, 0.9)",
        "home_button_pressed_bg": "rgba(0, 0, 0, 0.18)",
        "nav_button_bg": "transparent",
        "nav_button_text": "#f4efff",
        "nav_button_hover_bg": "rgba(244, 239, 255, 0.14)",
        "nav_button_pressed_bg": "rgba(0, 0, 0, 0.22)",
        "nav_button_active_bg": "#f4efff",
        "nav_button_active_text": "#1f1730",
    },
)

CRIMSON_THEME = create_theme(
    "crimson",
    {
        "app_bg": "#2b171b",
        "panel_bg": "#3d2228",
        "panel_bg_emphasis": "#321b20",
        "content_bg": "#351d23",
        "button_bg": "#4f2a32",
        "button_hover_bg": "#61343e",
        "button_active_bg": "#743f4b",
        "text_primary": "#fff0f2",
        "text_secondary": "#d9b7bd",
        "border": "#784a55",
        "home_button_bg": "#fff0f2",
        "home_button_text": "#2a1117",
        "home_button_hover_bg": "rgba(255, 240, 242, 0.9)",
        "home_button_pressed_bg": "rgba(0, 0, 0, 0.2)",
        "nav_button_bg": "transparent",
        "nav_button_text": "#fff0f2",
        "nav_button_hover_bg": "rgba(255, 240, 242, 0.14)",
        "nav_button_pressed_bg": "rgba(0, 0, 0, 0.24)",
        "nav_button_active_bg": "#fff0f2",
        "nav_button_active_text": "#2a1117",
    },
)

SLATE_THEME = create_theme(
    "slate",
    {
        "app_bg": "#e8ecf1",
        "panel_bg": "#d6dde6",
        "panel_bg_emphasis": "#c6d0dc",
        "content_bg": "#f5f7fa",
        "button_bg": "#cbd5df",
        "button_hover_bg": "#becbd8",
        "button_active_bg": "#afbdcc",
        "text_primary": "#1c2630",
        "text_secondary": "#566675",
        "border": "#aeb9c5",
        "home_button_bg": "#ffffff",
        "home_button_text": "#1c2630",
        "home_button_hover_bg": "rgba(255, 255, 255, 0.9)",
        "home_button_pressed_bg": "rgba(0, 0, 0, 0.1)",
        "nav_button_bg": "transparent",
        "nav_button_text": "#1c2630",
        "nav_button_hover_bg": "rgba(255, 255, 255, 0.55)",
        "nav_button_pressed_bg": "rgba(0, 0, 0, 0.1)",
        "nav_button_active_bg": "#ffffff",
        "nav_button_active_text": "#1c2630",
    },
)

MINT_THEME = create_theme(
    "mint",
    {
        "app_bg": "#edf6f2",
        "panel_bg": "#d8e9e1",
        "panel_bg_emphasis": "#c5ded2",
        "content_bg": "#f8fbf9",
        "button_bg": "#cce2d8",
        "button_hover_bg": "#bdd8cc",
        "button_active_bg": "#accbbd",
        "text_primary": "#1b2b24",
        "text_secondary": "#587064",
        "border": "#a7c2b5",
        "home_button_bg": "#ffffff",
        "home_button_text": "#1b2b24",
        "home_button_hover_bg": "rgba(255, 255, 255, 0.9)",
        "home_button_pressed_bg": "rgba(0, 0, 0, 0.1)",
        "nav_button_bg": "transparent",
        "nav_button_text": "#1b2b24",
        "nav_button_hover_bg": "rgba(255, 255, 255, 0.55)",
        "nav_button_pressed_bg": "rgba(0, 0, 0, 0.1)",
        "nav_button_active_bg": "#ffffff",
        "nav_button_active_text": "#1b2b24",
    },
)

SAND_THEME = create_theme(
    "sand",
    {
        "app_bg": "#f3efe6",
        "panel_bg": "#e2d8c8",
        "panel_bg_emphasis": "#d4c7b2",
        "content_bg": "#faf7f0",
        "button_bg": "#d8cbb9",
        "button_hover_bg": "#ccbea9",
        "button_active_bg": "#bdad95",
        "text_primary": "#2d261d",
        "text_secondary": "#6d5f4c",
        "border": "#b8a88f",
        "home_button_bg": "#ffffff",
        "home_button_text": "#2d261d",
        "home_button_hover_bg": "rgba(255, 255, 255, 0.9)",
        "home_button_pressed_bg": "rgba(0, 0, 0, 0.1)",
        "nav_button_bg": "transparent",
        "nav_button_text": "#2d261d",
        "nav_button_hover_bg": "rgba(255, 255, 255, 0.52)",
        "nav_button_pressed_bg": "rgba(0, 0, 0, 0.1)",
        "nav_button_active_bg": "#ffffff",
        "nav_button_active_text": "#2d261d",
    },
)

HIGH_CONTRAST_THEME = create_theme(
    "high_contrast",
    {
        "app_bg": "#000000",
        "panel_bg": "#111111",
        "panel_bg_emphasis": "#050505",
        "content_bg": "#000000",
        "button_bg": "#1f1f1f",
        "button_hover_bg": "#303030",
        "button_active_bg": "#ffffff",
        "text_primary": "#ffffff",
        "text_secondary": "#d8d8d8",
        "border": "#ffffff",
        "home_button_bg": "#ffffff",
        "home_button_text": "#000000",
        "home_button_hover_bg": "rgba(255, 255, 255, 0.88)",
        "home_button_pressed_bg": "rgba(255, 255, 255, 0.7)",
        "nav_button_bg": "transparent",
        "nav_button_text": "#ffffff",
        "nav_button_hover_bg": "rgba(255, 255, 255, 0.22)",
        "nav_button_pressed_bg": "rgba(255, 255, 255, 0.3)",
        "nav_button_active_bg": "#ffffff",
        "nav_button_active_text": "#000000",
    },
)

ALL_THEMES = {
    theme["name"]: theme
    for theme in (
        LIGHT_THEME,
        DARK_THEME,
        STEEL_THEME,
        GRAPHITE_THEME,
        OCEAN_THEME,
        FOREST_THEME,
        AMBER_THEME,
        VIOLET_THEME,
        CRIMSON_THEME,
        SLATE_THEME,
        MINT_THEME,
        SAND_THEME,
        HIGH_CONTRAST_THEME,
    )
}
